spring:
  cloud:
    gateway:
      routes:
        - id: test
          uri: http://localhost:8080
          predicates:
            - Path=/test/**
          filters:
            - StripPrefix=1
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY
                methods: GET,POST
                backoff:
                  firstBackoff: 10ms
                  maxBackoff: 50ms
                  factor: 2
                  basedOnPreviousValue: false

  codec:
    max-in-memory-size: 15MB
server:
  port: 8001
